### ISSUE TITLE
Problem in the demultiplexed files

### ISSUE THREAD

**Issue by Enorya** [asrivathsan/ONTbarcoder#2]
Hi @asrivathsan, I succeeded to run ONTbarcoder in order to demultiplexed my raw reads but I have a problem with the resulting demultiplexed files present in the demultiplexed/ folder. Indeed, the reads in the fasta files are not in IUPAC nucleotide code like you can see in the following file:
[example_demultiplexed_file.txt](https://github.com/asrivathsan/ONTbarcoder/files/6336543/example_demultiplexed_file.txt)

In the input file I have only ACTG characters. In the parameters I only changed the minimum length to 1400 (because my reads have a length between 1400 to 1670bp) and the length of barcode to 1400 also (by copying the example given with 658). I also changed the genetic code to the Standard Code. Otherwise, the other parameters remained unchanged.

Do you have any idea why I have this kind of results? Or maybe you have a suggestion on what settings I should put?

PS: Is there a way to contact you without opening an issue? Because I am not sure it is the best way

**Comment by asrivathsan** [comment]
Sure! I can be reached at asrivathsan@gmail.com, if you can just drop a mail, I can reply to the contents in this there.

**Comment by asrivathsan** [comment]
Just to add to this, this is expected behavior of ONT barcoder as it accounts for strand specific error rates for MAFFT alignments.

**Comment by OndroV** [comment]
Hello, thanks for asking this. I was wondering about the same. I guess that many other users would be grateful for a more elaborate explanation. @asrivathsan 
So how does this EFPQ code match with ACTG nucleotides, please?
Also, when we recode an EFPQ read to ACTG, do we get a "sense" sequence or a reverse complement of the respective ACTG read pairing with this EFPQ read? It would be nice to know this, if we want to analyze the demultiplexed files also with another software.
Cheers! Ondro

**Comment by asrivathsan** [comment]
Hi Ondro

If you want to obtain normal nucleotides you can replace as follows:

        E->A
        F->G
        Q->C
        P->T

This should give you the desired file. One doesn't need to reverse complement prior to changing.
