### ISSUE TITLE
Installation for MacOS

### ISSUE THREAD

**Issue by ramongallego** [asrivathsan/ONTbarcoder#4]
Hi there,

I downloaded and unzip the release (v.1.0.8)zip file for a MacOSX -, unzip it and there is no executable file that I can see. A lot of python libraries but  no obvious way of starting the GUI - any pointers? I have tried opening the unix executable ONT_barcoder_multiprocessing but the OS does not like opening any of the pythonlibs downloaded from the internet

**Comment by asrivathsan** [comment]
Hi, the executable should be ONTbarcoder_multiprocessing. There are a large number of executables there, so one has to look for that one. We have made some changes for the Mac version to make things easier, I will uploading it within a few days, so a better version for mac is on the way.

**Comment by ramongallego** [comment]
Sounds great. Looking forward to it

**Comment by asrivathsan** [comment]
Hi, we have uploaded v.0.1.9. hope it goes smoothly.
