### ISSUE TITLE
Getting stuck on demultiplexing

### ISSUE THREAD

**Issue by adsweet** [asrivathsan/ONTbarcoder#8]
Hi,

Thanks for developing ONTbarcocer! I've successfully used the program on some of my own data and with your example data set. However, my most recent run keeps getting stuck on the Demultiplexing step. I'm able to load in my CSV and FASTQ files and start the run, but the progress bar gets stuck about 20% into demultiplexing. Some temp files are produced in the 1_demultiplexing directory, but it doesn't progress any further. I'd appreciate any guidance!

Best,

Drew

**Comment by asrivathsan** [comment]
Dear Drew,

The most common reason this error comes is when there are spaces or some unusual characters in the sample ID, could you once check for spaces there?

I have uploaded ONTbarcoder2 and have included the space replacement internally in it. Please feel free to test it out, it should be a pre-release at the moment.

cheers
Amrita

**Comment by adsweet** [comment]
Thanks for your quick response, Amrita! Using version 2 worked. I’ll look for the Mac version when it’s released!

Thanks again,

Drew

**Comment by asrivathsan** [comment]
Glad that resolved it!
